### ISSUE TITLE
Base Game Checklist

### ISSUE THREAD

**Issue by WilliamHayward** [LipwigJS/LipwigAgainstHumanity#1]
This is everything I want for the most basest barest project

# Host
- [ ] Game Setup Menus
- [ ] Join Screen
- [ ] Waiting screens
- [ ] Card presentation
- [ ] Scoring/Score presentation
- [ ] Deck management

# Client
- [ ] Waiting screens
## Card Czar
- [ ] Present black card (read out then move to host)
- [ ] Choose winning white card
## Players
- [ ] Select white card
